on:
  push:                 
    branches:           
      - main    
name: Deploy  
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master        
      - uses: SamKirkland/FTP-Deploy-Action@2.0.0   
        env:                                        
          FTP_SERVER: mh.rsw.jp
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }} 
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} 
          LOCAL_DIR: ./                          
          REMOTE_DIR: /data.taka.ml
        with:
          exclude: |
            **/.git*
            **/.git*/**
            LICENSE
            README.md
            example.config.php